def possible_mRNA_seq(aa_seq):
    codons_dict={"A":["GCU","GCC","GCA","GCG"],
        "C":["UGU","UGC"],
        "D":["GAU","GAC"],
        "E":["GAA","GAG"],
        "F":["UUU","UUC"], 
        "G":["GGU","GGC","GGA","GGG"], 
        "H":["CAU","CAC"],
        "I":["AUU","AUC","AUA"],
        "K":["AAA","AAG"],
        "L":["CUU","CUC","UUA","UUG","CUG","CUA"], 
        "M":["AUG"],
        "N":["AAU","AAC"],
        "P":["CCU","CCC","CCA","CCG"],
        "Q":["CAA","CAG"],
        "R":["CGU","CGC","CGA","CGG","AGA","AGG"],
        "S":["UCU","UCC","UCA","UCG","AGU","AGC"],
        "T":["ACU","ACC","ACA","ACG"],
        "V":["GUU","GUC","GUA","GUG"],
        "W":["UGG"],
        "Y":["UAU","UAC"],
        "STOP":["UAA","UAG", "UGA"]}
    
    frequency={}
    
    
    for i in codons_dict.keys():
        frequency[i]=len(codons_dict[i])
        
    

    
    mRNA_opt = frequency["STOP"]
    for j in aa_seq:
        mRNA_opt = mRNA_opt*(frequency[j])
        
    
        
    counter= (mRNA_opt % 1000000)
    
    print (counter)

        

possible_mRNA_seq("MAEGPILCCFAEEQFWGACLCMWLRSKFWACSIPQAMQWAEEGDWPAMNGVNDDGLDIVYYKKMKGSYMMDRIATIEGMRGAYVIMQCHKCMAGTFMHYHPYYPAQDQAKFAGPQKGSDLWFRCCGQSSRGGEMEGLGPGITHSRWEVSAIFSDLPLESLKLQDRITITNYWYAPWWRRMVHFAQGFLSASAIYRTQNRLDNLTDKLGAKNTRSFTGTNLCALNMADMFWRDSVPPDMWQWTKHMKNIFGEAKCYEHCFHASNSYMWSHLAHYNCCIISALWIRRAVFHCGAGTMAAMFVLFDKMDPQHLIGVWYGCMKSTHSIEIFRTRRGAYEFRHSQDGCDLPNPNFDGGLMLYKAHWRLCEAVMFHTHQRLCPMFGCYAKPDNYVNRGHWRYCCINDYQDIWSPKLLDEVMKIQICGTTLHWRFHFSTIDCCGCGPPDLYSENLVSYMLCCATAIHQRRPKDYKWFVTEVSVFQIIEVWSKQVGGFERMSYDWFMVVQEKNHECVMVINSGPSDLEYPGCPEGPNSMKIHAIDDGCYADTAHCYLVKVCMHMCWHEYGQAHKMQEYDLDKKGMCINSWKEISIHQQDHAPTAKRHRLDKARFVFWVMASGDMVQLMMGDWIKWTMEQFCEHHSNTYVNILRPNMWDRYNLCGDDKCDAWMDVLYEFSPLGFDLSSWHILEEQCAPYCLQQTMIHHKTRKAYMCSACEMRVGSTPNQAEHCNSNDEQLAHNGSEMWQPSKSRNRPQRDPLNNYEVYCRAEWSVCPLFMPCPYQFKRDCTKNAWILCIEMQGNQATQYAFCLKHMVVQSTFNAVHQTWERFHPNECIDQSWGYGTRRYETSHVCERSYYGYLSSTDKWTIILWDIAGATAGTSWYVHRVQYTFPMPAHWVWDGVDHPCQTDNVGFMTCQPWANKMMILPRRQASMFGFMFEISQHKCTGWRYWGQPWDHGVLDMMKCIPHADNCHGWFWADERTTPWEPYSGCCNCVRSFPMARFT")


        
 