def find_motif(seq1, motif):
    from Bio import motifs
    from Bio.Seq import Seq
    instances= [Seq(motif)]
    seq1= Seq(seq1)
    m=motifs.create(instances)
    found=[]
   
   
    for pos, seq in m.instances.search(seq1):
       found.append(pos+1)

    print(found)
        
            
        
    

find_motif("AGTTCTTTGGAATTCTTTGGGTTCTTTGCCGGATTTCTTTGTTCTTTGTTGGTTCTTTGATTTCTTTGGCTTCTTTGATTTCTTTGGACGAATGGTTCTTTGCTTCTTTGTATAACTTCTTTGTTCTTTGATATTTCTTTGTTCTTTGCTACGTTCTTTGCATTCTTTGTTCTTTGTACCTGTTTCTTTGTCTCATTTCTTTGTTCTTTGTTCTTTGACACTATTCTTTGCGCGTTCTTTGCTTCTTTGTTCTTTGTTTCTTTGTGCACTGTGATGAGTTTCTTTGTTCTTTGGTTGTTCTTTGCATATCTTCTTTGCTTCTTTGCCGCTTCTTTGTTCTTTGTTCTTTGCGTTTCTTTGATTCTTTGCGGGCTTCTTTGCTTCTTTGGGACTTCTTTGGCCTTCTTTGTTCTTTGTTCTTTGTTGTTTCTTTGTCCGTTCTTTGATTCTTTGGTTCTTTGACAGTTTCTTTGGGTTCTTTGGTTCTTTGCTTTCTTTGGAGGCCTGAACGTTCTTTGTTCTTTGTCGGCGAAAGTACTTCTTTGCGGTTGTTCTTCTTTGGTTCTTTGATTTCTTTGCTTCTTTGGCTTCTTTGGATTCTTTGTTCTTTGTCTTCTTTGCATACTTCTTTGATTCTTTGTGCTTCTTTGTTTCTTTGTTCTTTGGTTCTTTGCTCGTCTCTTCTTTGTTTCTTTGTTTCTTTGTTCTTTGCATTCTTTGGCGCTTCTTTGAAATGGTTCTTTGCATTTCTTTGTTCTTTGTCTTCTTTGATGTCGAGTGAGTGTTCTTTGTTCTTTGTTCTTTGATTCTTTGTCTTCTTTGTGGAGTGTTACTTCTTTGCACCTTCTTTGTTCTTTGGTTCTTTGAAAGCAATCAATTCTTTGTTTTCTTTGTTCTTTGCCTTCTTTGTTCTTTGTCCTTTCTTTGATGTTCTTTGCGGCTGGTTCTTTGTTCTTTGTTTCTTTGATCAATCAATTCTTTGTTTTCTTTG","TTCTTTGTT")
